# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7c376bcf4fc892ed19f8ca172a9948c4700eef72765ca7aa219b00356cae9e5c43503b68f1a5d54a2fe636626b703567c02b0e0aaf0c89a21b78f40c0a1743c

test:
  secret_key_base: e4c4a89915b5c003dcd935ec3e045f5bea2bae490df4ef77f23ba3f80ec0f1010d6f61ac1c0ef330142901ba07bf014fd55b62d5af647f416dff40f6fe6bb844

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
